### ISSUE TITLE
在Android上运行报错，TabBarItemIOS

### ISSUE THREAD

**Issue by wx409790282** [EleTeam/Shop-React-Native#1]
首先非常感谢EleTeam的奉献，让我有机会用这个项目学习RN
在git clone，npm install，安装vector Icon并重运行后，运行react-native run-android遇到这样一个错误
![image](https://cloud.githubusercontent.com/assets/10881838/18409657/774e9fd4-777f-11e6-971e-4b7656b355fb.png)
根据报错似乎是android上使用了ios控件无法运行，请问如何解决呢？谢谢

**Comment by EleTeam** [comment]
非常感谢你提出这个问题，现在已经修复了，请更新代码，再运行。

**Comment by wx409790282** [comment]
谢谢，已更新，正常运行。
