### ISSUE TITLE
Application ShopReactNative has not been registered

### ISSUE THREAD

**Issue by sidealice** [EleTeam/Shop-React-Native#3]
请教下错误是啥意思

Application ShopReactNative has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.

runApplication
    AppRegistry.js:93
__callFunction
    MessageQueue.js:229
<unknown>
    MessageQueue.js:111
guard
    MessageQueue.js:42
callFunctionReturnFlushedQueue
    MessageQueue.js:110

**Comment by EleTeam** [comment]
1.更新到最新版本的react native。2.不要更改项目的名字和文件夹
